import test from 'node:test';import assert from 'node:assert/strict';
import {FightEngine,Fighter,CHARACTERS,WORLD,FIXED_STEP,fighterPose} from '../src/engine.js';
import {capoeiraHurt} from '../src/capoeira.js';import {FIGHTING_STYLES} from '../src/styles.js';
const advance=(g,s)=>{for(let i=0;i<s/FIXED_STEP;i++)g.update(FIXED_STEP)};
function scene(slot=0){const events=[],g=new FightEngine({onEvent:e=>events.push(e)});g.start(slot===0?'gelton':'rafael','local',slot===0?'rafael':'gelton');g.phase='fight';g.fighters[0].x=450;g.fighters[1].x=640;return {g,events,f:g.fighters[slot],target:g.fighters[1-slot],slot}}
test('Gelton tem estilo próprio, ginga de quatro poses e seleção nos dois slots',()=>{assert.equal(FIGHTING_STYLES.gelton.name,'Capoeira');assert.equal(CHARACTERS.gelton.name,'Prof. Gelton');const f=new Fighter('gelton',0);let poses=[];for(let i=0;i<4;i++){f.animTime=i/8+.001;poses.push(fighterPose(f).index)}assert.deepEqual(poses,[0,1,2,3]);for(const slot of [0,1]){const s=scene(slot);s.g.queue(slot,'kick');advance(s.g,.7);assert.ok(s.target.hp<1000)}});
test('rasteira em capoeira exige defesa baixa; armada e aú são poses completas distintas',()=>{for(const down of [false,true]){const s=scene();s.g.setInput(1,{block:true,down});s.g.setInput(0,{down:true});s.g.queue(0,'kick');advance(s.g,.8);assert.equal(s.events.some(e=>e.type==='block'),down);assert.equal(s.target.hp<1000,!down)}const s=scene();for(const [move,index]of [['kick',2],['sweep',6],['airKick',10]]){s.f.action=s.f.state=move;s.f.moveData={startup:.1,active:.2};s.f.actionTime=.15;assert.deepEqual(fighterPose(s.f),{atlas:'combat',index})}});
test('colisões de Gelton são espelhadas e abaixam junto com a esquiva desenhada',()=>{const f=new Fighter('gelton',0);for(const state of ['idle','walk','crouch','sweep','uppercut','block','hit']){f.state=state;for(const direction of [-1,1]){f.direction=direction;assert.deepEqual(f.hurtboxes,capoeiraHurt(f).map(([x,h,w,height])=>({x:f.x+(direction>0?x:-x-w),y:f.y-h,w,h:height})))}}f.state='crouch';assert.ok(f.hurtboxes.every(b=>b.y>=WORLD.floor-192-.01))});
test('pincelada e aú funcionam sem barra; Roda das Artes custa 100 e emite cinco ondas cromáticas',()=>{for(const move of ['special','uppercut','super']){const s=scene();s.f.x=260;s.target.x=900;if(move==='super')s.f.meter=100;s.g.queue(0,move);advance(s.g,2);assert.equal(s.events.filter(e=>e.type==='special'&&e.move===move).length,1);if(move==='super'){assert.equal(s.events.filter(e=>e.type==='projectile').length,5);assert.equal(s.f.meter,0)}if(move==='special')assert.ok(s.target.hp<1000)}});
test('Gelton joga contra todos os personagens sem perfis ausentes ou números inválidos',()=>{for(const id of Object.keys(CHARACTERS)){if(id==='gelton')continue;const g=new FightEngine({random:()=>.37});g.start('gelton','cpu',id);g.phase='fight';for(let i=0;i<2400;i++){if(i%80===0)g.queue(0,i%160?'kick':'special');if(i%500===0){g.fighters[0].meter=100;g.queue(0,'super')}g.update(FIXED_STEP)}assert.ok(g.fighters.every(f=>[f.x,f.y,f.hp,f.meter].every(Number.isFinite)))}});
