import test from 'node:test';import assert from 'node:assert/strict';
import {FightEngine,FIXED_STEP,WORLD} from '../src/engine.js';
const advance=(g,s)=>{for(let n=0;n<Math.ceil(s/FIXED_STEP);n++)g.update(FIXED_STEP)};
function scene(slot=0,id='rafael'){let events=[];const g=new FightEngine({random:()=>.5,onEvent:e=>events.push(e)});g.start(slot===0?'marcelo':id,'local',slot===0?id:'marcelo');g.phase='fight';const f=g.fighters[slot],target=g.fighters[1-slot];f.x=slot?970:310;target.x=slot?310:970;return {g,f,target,events,slot}}
function deploy(s,move='super'){s.f.meter=100;s.g.queue(s.slot,move);advance(s.g,.6);assert.equal(s.events.filter(e=>e.type==='droneDeploy').length,6)}
test('enxame exige 100% de barra; atalho drone também consome a barra completa',()=>{for(const move of ['super','drone']){const s=scene();s.f.meter=99;s.g.queue(0,move);advance(s.g,.5);assert.equal(s.g.drones.length,0);assert.equal(s.f.meter,99);deploy(s,move);assert.equal(s.f.meter,0)}});
test('seis drones voam acima da arena e disparam seis lasers diagonais, nos dois lados e contra todos os rivais',()=>{for(const slot of [0,1])for(const id of ['rafael','gustavo','gelton']){const s=scene(slot,id);deploy(s);assert.ok(s.g.drones.every(d=>d.y<WORLD.floor-250));advance(s.g,3);assert.equal(s.events.filter(e=>e.type==='droneFire').length,6);assert.equal(s.events.filter(e=>e.type==='hit').length,6);assert.ok(s.target.hp<800);assert.equal(s.f.meter,0);assert.equal(s.g.drones.length,0)}});
test('todos os disparos podem ser defendidos alto ou baixo e não reabastecem o super',()=>{for(const slot of [0,1])for(const down of [false,true]){const s=scene(slot);s.g.setInput(1-slot,{block:true,down});deploy(s);advance(s.g,3);assert.equal(s.events.filter(e=>e.type==='hit').length,0);assert.equal(s.events.filter(e=>e.type==='block').length,6);assert.ok(s.target.hp>=970);assert.equal(s.f.meter,0)}});
test('enxame mira na altura do corpo em pé, agachado e no ar',()=>{for(const posture of ['stand','crouch','air']){const s=scene();if(posture==='crouch')s.g.setInput(1,{down:true});if(posture==='air'){s.target.y=WORLD.floor-120;s.target.vy=-700;}deploy(s);advance(s.g,3);assert.ok(s.target.hp<1000);assert.equal(s.events.filter(e=>e.type==='droneFire').length,6)}});
test('invulnerabilidade e queda não são atravessadas pelos lasers; drones expiram se não há alvo',()=>{for(const type of ['invulnerable','knocked']){const s=scene();deploy(s);if(type==='invulnerable')s.target.invincible=10;else{s.target.knocked=true;s.target.knockdownTime=10;}advance(s.g,4);assert.equal(s.target.hp,1000);assert.equal(s.g.drones.length,0)}});
test('mira travada permite evitar um pulso com deslocamento posterior',()=>{const s=scene();deploy(s);let guard=0;while(!s.g.drones[0]?.aim&&guard++<200)s.g.update(FIXED_STEP);const d=s.g.drones[0];assert.ok(d.aim);s.target.x=500;while(!d.fired&&guard++<400)s.g.update(FIXED_STEP);assert.ok(d.fired);assert.equal(s.target.hp,1000)});
test('pausa e hitstop congelam o enxame; troca de round limpa drones e lasers',()=>{const s=scene();deploy(s);let age=s.g.drones[0].age;s.g.togglePause();advance(s.g,1);assert.equal(s.g.drones[0].age,age);s.g.togglePause();s.g.freeze=.3;advance(s.g,.2);assert.equal(s.g.drones[0].age,age);s.f.meter=41;s.g.newRound();assert.equal(s.g.drones.length,0);assert.equal(s.g.lasers.length,0);assert.equal(s.f.meter,41)});
test('o enxame continua autônomo quando Marcelo recebe um golpe e não pode ser empilhado',()=>{const s=scene();deploy(s);s.f.meter=100;assert.equal(s.g.beginMove(s.f,'super'),false);s.g.hit({attacker:s.target,target:s.f,move:'punch',x:s.f.x,y:s.f.y-200});advance(s.g,3);assert.equal(s.events.filter(e=>e.type==='droneDeploy').length,6);assert.equal(s.events.filter(e=>e.type==='droneFire').length,6)});
test('ataque normal e firewall do Marcelo permanecem; Gelton, Rafael e Gustavo não invocam drones',()=>{for(const id of ['gelton','rafael','gustavo']){const g=new FightEngine();g.start(id,'local','marcelo');g.phase='fight';g.fighters[0].meter=100;g.queue(0,'drone');assert.equal(g.fighters[0].buffer,null);assert.ok(g.beginMove(g.fighters[0],'special'))}for(const move of ['special','uppercut']){const s=scene();s.g.queue(0,move);advance(s.g,1);assert.equal(s.events.filter(e=>e.type==='special'&&e.move===move).length,1)}});
test('teclas Z/I, L3 e botão de toque continuam ligadas ao atalho do super de Marcelo',async()=>{const fs=await import('node:fs/promises');const input=await fs.readFile(new URL('../src/input.js',import.meta.url),'utf8');assert.ok(input.includes("KeyZ:'drone:1'"));assert.ok(input.includes("KeyI:'drone:1'"));const html=await fs.readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(html.includes('data-action="drone"'));assert.ok(html.includes('ENXAME'))});
