"""Compile nine reviewed native enemy sheets without destroying original art.

Detached components have spatial ownership. The four approved v4 clips and the
three articulated mechanical rigs are retained. No combat behaviour is changed.
"""
from pathlib import Path
import json
import numpy as np
from PIL import Image
from scipy import ndimage
from sprite_geometry import landmarks

ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'assets/story'
SOURCE=ROOT/'assets/source'
HEIGHTS={'vial':190,'scanner':210,'projector':195,'book':135,'archaeologist':140,'aula':285,'fairRobot':340,'exo':350,'substitute':285}
BIPED={'lab','elite','kungfu','inspector','fairRobot','exo','substitute'}
metadata=json.loads((ART/'enemy-animation-v4.json').read_text())

def extract(path):
    a=np.array(Image.open(path).convert('RGBA'));h,w=a.shape[:2]
    labels,n=ndimage.label(a[:,:,3]>100,np.ones((3,3)));sizes=np.bincount(labels.ravel());objects=ndimage.find_objects(labels)
    major=[(i,o) for i,o in enumerate(objects,1) if o and sizes[i]>5000]
    assert len(major)==16,(path.name,'expected 16 complete owned silhouettes',len(major))
    major.sort(key=lambda pair:(pair[1][0].start+pair[1][0].stop)/2)
    ordered=[]
    for row in range(4):ordered.extend(sorted(major[row*4:row*4+4],key=lambda pair:pair[1][1].start))
    major_ids={i for i,_ in major};result=[]
    for index,(ident,obj) in enumerate(ordered):
        mask=labels==ident;count=0
        for k,part in enumerate(objects,1):
            if not part or k in major_ids or sizes[k]<4:continue
            cy=(part[0].start+part[0].stop)/2;cx=(part[1].start+part[1].stop)/2
            near=min(ordered,key=lambda pair:(cx-(pair[1][1].start+pair[1][1].stop)/2)**2+(cy-(pair[1][0].start+pair[1][0].stop)/2)**2)[0]
            gap=np.hypot(max(0,obj[1].start-part[1].stop,part[1].start-obj[1].stop),max(0,obj[0].start-part[0].stop,part[0].start-obj[0].stop))
            if near==ident and (gap<12 or sizes[k]>36 and obj[1].start-8<=cx<=obj[1].stop+8 and obj[0].start-8<=cy<=obj[0].stop+8):mask|=labels==k;count+=1
        mask=ndimage.binary_dilation(mask,iterations=2)
        yy,xx=np.nonzero(mask);x0=max(0,int(xx.min())-3);y0=max(0,int(yy.min())-3);x1=min(w,int(xx.max())+4);y1=min(h,int(yy.max())+4)
        tile=a[y0:y1,x0:x1].copy();tile[~mask[y0:y1,x0:x1]]=0
        im=Image.new('RGBA',(tile.shape[1]+6,tile.shape[0]+6));im.alpha_composite(Image.fromarray(tile),(3,3))
        result.append((im,{'sourceBounds':[x0,y0,x1-x0,y1-y0],'ownedDetachedComponents':count}))
    return result

for kind,height in HEIGHTS.items():
    frames=extract(SOURCE/f'{kind}-animation-v7.png')
    scale=height/float(np.median([im.height-6 for im,_ in frames[:9]]))
    packed=Image.new('RGBA',(2048,3000));x=y=3;row=0;profiles=[]
    for index,(im,source) in enumerate(frames):
        if x+im.width+3>2048:x=3;y+=row+3;row=0
        a=np.array(im)[:,:,3]>100;xx=np.nonzero(a[round(im.height*.46):round(im.height*.66)])[1]
        anchor=float(np.median(xx)) if len(xx) and index<13 else im.width*.5
        bottom=im.height-3
        profile={'rect':[x,y,im.width,im.height],'anchorX':round(anchor,4),'bottom':bottom,'height':im.height,'scale':round(scale,8),'source':f'assets/source/{kind}-animation-v7.png',**source}
        if kind in BIPED and index<=8:profile['landmarks']=landmarks(im,anchor);profile['headBottom']=im.height*.245
        profiles.append(profile);packed.alpha_composite(im,(x,y));x+=im.width+3;row=max(row,im.height)
    assert y+row+3<packed.height
    output=ART/f'{kind}-animation-v7.webp';temporary=output.with_suffix('.tmp.webp')
    packed.crop((0,0,2048,y+row+3)).save(temporary,lossless=True,method=6)
    assert temporary.stat().st_size>1000
    with Image.open(temporary) as verified:verified.verify()
    temporary.replace(output)
    metadata[kind]={'file':f'assets/story/{kind}-animation-v7.webp','scale':round(scale,8),'frames':profiles,'schemaVersion':2,'clips':{'idle':[0],'walk':list(range(1,9)),'attack':[9,10,11],'damage':[12],'defeat':[13,14,15]}}
    print(kind,len(profiles),'poses, constant scale',round(scale,4))

geometry={}
for kind,sheet in metadata.items():
    if kind not in BIPED:continue
    image=Image.open(ROOT/sheet['file']).convert('RGBA');poses=[]
    for index,f in enumerate(sheet['frames'][:9]):
        x,y,w,h=f['rect'];im=image.crop((x,y,x+w,y+h));s=f.get('scale',sheet['scale']);axis=f['anchorX'];bottom=f['bottom']
        points=f.get('landmarks') or landmarks(im,axis)
        poses.append({'points':[[(px-axis)*s,(py-bottom)*s] for px,py in points],'headBottom':(h*.245-bottom)*s})
    geometry[f'{kind}:enemy']=poses
(ART/'enemy-animation-v7.json').write_text(json.dumps(metadata,separators=(',',':'))+'\n')
(ROOT/'src/enemy-motion-data.js').write_text('// Native source landmarks, generated by prepare-enemy-animation.py.\nexport const ENEMY_MOTION='+json.dumps(geometry,separators=(',',':'))+';\n')
